version: '3.7'

services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data